apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: konflux-banner-production-stone-prd-rh01
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/testcara/konflux-banner.git
    targetRevision: main
    path: deploy/production/stone-prd-rh01
  destination:
    server: https://kubernetes.default.svc
    namespace: konflux-banner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
